name: Test using JUnit5
on:
  pull_request:

jobs:
  name: Build and Run Tests
  runs-on: ubuntu-latest
  steps:
  - name: Set up JDK 8
    uses: actions/setup-java@v3
    with:
      java-version: '8'
      distribution: 'temurin'
  - name: Fix execution permissions
    run: chmod +x gradlew
  - name: Build with Gradle
    run: ./gradlew build
  - name: Checkout Code
    uses: actions/checkout@v1
  - name: Execute test
    run: ./gradlew test
  - name: Publish Test Report
    uses: mikepenz/action-junit-report@v3
    if: success() || failure() # always run even if the previous step fails
    with:
      report_paths: '**/build/test-results/test/TEST-*.xml'
